### ISSUE TITLE
Any plan to add other ThinQ Devices? LG GSJ761PZZZ Side-by-Side 

### ISSUE THREAD

**Issue by DJay-X** [sman591/homebridge-lg-thinq-ac#21]
@sman591 I hope not to bother, but I can't find any other solution for ThinQ -> Homebridge and the experience you show with your plugin.

Do you have any plans to support more ThinQ devices in the future or create another ThinQ plugin? I was hoping to use my [Fridge LG GSJ761PZZZ](https://www.lg.com/de/kuehlschraenke-gefrierschraenke/lg-GSJ761PZZZ) showing Temperature in HomeKit.

If there is anything I can do to help from user side, please of course let me know.

Thanks again for the time you are investing and for your work sharing with the community. 👍

**Comment by sman591** [comment]
@DJay-X I only have my one A/C unit, so I don't have any plans to add additional product support at this time.

Does your Fridge LG GSJ761PZZZ show up with this plugin at all? It might not be hard to add basic temperature support but I'm not sure what the API response is like

**Comment by DJay-X** [comment]
@sman591 Thanks for your friendly reply.
I received the new fridge a couple of days ago and now I was able to just give the plugin a shot out of curiosity. :)

```
Jun 13 23:41:59 raspberrypi-3BPlus homebridge[3786]: [2020-6-13 23:41:59] Loaded plugin: homebridge-lg-thinq-ac@1.4.1
Jun 13 23:41:59 raspberrypi-3BPlus homebridge[3786]: [2020-6-13 23:41:59] Registering platform 'homebridge-lg-thinq-ac.LgThinqAirConditioner'
Jun 13 23:42:00 raspberrypi-3BPlus homebridge[3786]: [2020-6-13 23:42:00] [LgThinqAirConditioner] Initializing LgThinqAirConditioner platform...
Jun 13 23:42:01 raspberrypi-3BPlus homebridge[3786]: [2020-6-13 23:42:01] [LgThinqAirConditioner] Initiating auth with provided redirect URL
Jun 13 23:42:04 raspberrypi-3BPlus homebridge[3786]: [2020-6-13 23:42:04] [LgThinqAirConditioner] Discover found 1 total devices
```
There is 1 device discovered but nothing (of course?) is showing up in HomeKit. 
Well... it's fridge, not an A/C. 😅

However, in the meantime I was also able to get to grips with the LG ThinQ app and it is completely useless for the fridge. 
The temperature of the fridge and freezer can be changed, Express Freeze can be switched on/off, but the current actual temperature of the device is not displayed at all. 
As if you constantly change the temperature of your fridge and need the app for that?! The obvious idea of displaying the real temperature seems too abstract for the LG developers. 

Buy this I don't think it's worth to put energy and work into further investigation? Especially if there was no general intention on your part to develop the app for other LG devices.

Let me know what you think and of course you can close this ticket.
Thanks again for being a developer and sharing your work with the community. 👍

**Comment by sman591** [comment]
>The temperature of the fridge and freezer can be changed, Express Freeze can be switched on/off, but the current actual temperature of the device is not displayed at all.

Ah, that's unfortunate 😞 yeah, doesn't sound like something this plugin will support in the near term given the controls/state would be pretty different.
