### ISSUE TITLE
 Error initializing platform

### ISSUE THREAD

**Issue by AmauryVela** [sman591/homebridge-lg-thinq-ac#25]
**Describe the bug**
I have this error on my console 

[LgThinqAirConditioner] Error initializing platform Error: getaddrinfo EAI_AGAIN route.lgthinq.com route.lgthinq.com:46030

**Symptom check**
* **Does your unit appear in the Home app?** No
* **Is the current on/off state, temperature, and mode being reported?** No
* **Does your unit respond to the controls?**No

**Relevant logs**
[LgThinqAirConditioner] Error initializing platform Error: getaddrinfo EAI_AGAIN route.lgthinq.com route.lgthinq.com:46030

Also the 
Login URL (paste this into your browser)
is empty

**Comment by sman591** [comment]
This sounds like a networking error. Could you try restarting the system that hosts Homebridge? Or if this is in a container, restart the container? If that still doesn't work, could you paste the response of `nslookup route.lgthinq.com`?

**Comment by AmauryVela** [comment]
Hi @sman591 thank you very much! that worked.
