### ISSUE TITLE
Temperature should optionally be available as a separate sensor in HomeKit

### ISSUE THREAD

**Issue by srshearer** [sman591/homebridge-lg-thinq-ac#41]
The AC unit's current temperature is not exposed as a temperature sensor in HomeKit. It would be ideal if there was an optional config parameter to add a the current temperature as a separate sensor so that it could be used for automations. A similar approach was taken to expose various sensors in [this Dyson plugin](https://github.com/joe-ng/homebridge-dyson-link#readme).

**Comment by sman591** [comment]
I implemented this a few months back and determined the Home app somehow didn't allow sensor-driven automation for the sensor I exposed. The Dyson implementation looks very similar though so I'm not sure what happened; can give it another shot

**Comment by sman591** [comment]
@srshearer Could you attach a screenshot of what sensors you see with the Dyson plugin? I tried this again and am not seeing anything on the "sensor automation" screen despite activating a temperature sensor.

![IMG_3052](https://user-images.githubusercontent.com/1441807/92421994-20d86c00-f130-11ea-84b3-738ec20c1d81.PNG)
![IMG_3053](https://user-images.githubusercontent.com/1441807/92421996-21710280-f130-11ea-9559-f6d99fd85d4d.PNG)

**Comment by srshearer** [comment]
Strange. First of all you are right, I do not see any temperature sensors. What I do see is a sensor for air quality. I must have seen the Dyson fan as an option for automation sensors and made an assumption.


![IMG_3351](https://user-images.githubusercontent.com/4999779/92425737-f93bd080-f13c-11ea-9322-686a99a97bb0.PNG)
![IMG_3353](https://user-images.githubusercontent.com/4999779/92425744-fc36c100-f13c-11ea-85fa-a06312bbaf7e.PNG)

**Comment by sman591** [comment]
Aha, yeah that's very strange.

I'll keep a branch open in case this changes for future iOS versions, but until then, I'm going to close this.

Note other temperature-based actions can be created using the Shortcuts app if/else conditions, though you can't have temperature be a trigger for that unless Apple implements this. Time/occupancy/Siri/etc can still be a trigger though
