### ISSUE TITLE
Multiple LG AC units only shows 1 unit inside homekit

### ISSUE THREAD

**Issue by SausCode** [sman591/homebridge-lg-thinq-ac#44]
**LG Air Conditioner Model**
Please provide your A/C model here. If the unit successfully paired to Homekit, please also include the "Model" listed in the accessory's settings.

LW1517IVSM
LP1419IVSM

The LW1517IVSM shows up inside homekit, perhaps coincidentally I set that one up first and it is the first one listed inside the ThinQ app. The model number inside homekit is: WIN_056905_WW

**Describe the bug**
I have two LG ac units inside thinq, only one shows up inside homekit

**Symptom check**
* **Does your unit appear in the Home app?** Yes/No - Both, only one of the two is visible
* **Is the current on/off state, temperature, and mode being reported?** Yes/No - Yes for the one that is available
* **Does your unit respond to the controls?** Yes/No - Yes for the one that is available

**Comment by sman591** [comment]
Hi @SausCode -- Could you restart Homebridge and check the Homebridge logs to see if there's a note about one of them not being supported?

**Comment by SausCode** [comment]
Hi @sman591, thanks for the reply.

`[LgThinqAirConditioner] "Portable" (model POT_056905_WW) uses the thinq1 platform, which is not supported. Please see https://github.com/sman591/homebridge-lg-thinq-ac/issues/4 for updates.`

Sorry for the noise, new to homebridge and HOOBS and didn't realize there was output I could actually see.

**Comment by SausCode** [comment]
Also, perhaps a separate issue is more appropriate, but seeing a good amount of spam in the logs with the functioning A/C:

...
10/2/2020, 1:57:45 PM [LgThinqAirConditioner] TargetHeaterCoolerStateCharacteristic: Error parsing state Error: Unsupported API value: 8
10/2/2020, 1:58:45 PM [LgThinqAirConditioner] TargetHeaterCoolerStateCharacteristic: Error parsing state Error: Unsupported API value: 8
...

**Comment by SausCode** [comment]
> Also, perhaps a separate issue is more appropriate, but seeing a good amount of spam in the logs with the functioning A/C:
> 
> ```
> ...
> 10/2/2020, 1:57:45 PM [LgThinqAirConditioner] TargetHeaterCoolerStateCharacteristic: Error parsing state Error: Unsupported API value: 8
> 10/2/2020, 1:58:45 PM [LgThinqAirConditioner] TargetHeaterCoolerStateCharacteristic: Error parsing state Error: Unsupported API value: 8
> ...
> ```

I think this is due to the A/C being on Energy Saver Mode, with it off I no longer see the messages in the logs.

**Comment by sman591** [comment]
Gotcha! Yeah looks like one of them isn't supported right now. #4 will be updated once support is added.

As for the energy saver mode -- this is a known bug that I believe should have a fix available later with a toggle for this support
