### ISSUE TITLE
Ability to disable/hide a device

### ISSUE THREAD

**Issue by kb1ibt** [sman591/homebridge-lg-thinq-ac#45]
My ACs are window ACs, which I have taken out because the temps are getting lower. Once the ACs have been unplugged for a while they report:
```[LgThinqAirConditioner] Error renewing monitor Error: Request failed with status code 400```
Is there a way to disable devices that I know will not be checking in for months?

What I'd like is a way to go into the config.json and add the accessory name to a block list so that way it will be hidden and not updated.

**Comment by sman591** [comment]
Thanks for flagging - that's definitely something we should support

**Comment by sman591** [comment]
Are you still seeing this? 

When you have your AC unplugged, have you removed it from your LG app? Or does it still display in the app?

**Comment by kb1ibt** [comment]
![IMG_0945](https://user-images.githubusercontent.com/142315/115341361-73721000-a176-11eb-8973-130527f1081c.png)
It is still in the app and showing as disconnected, and yes, the logs are still being cluttered with the error 400.
<img width="1026" alt="errors" src="https://user-images.githubusercontent.com/142315/115341494-be8c2300-a176-11eb-969d-2efcfb12ff7a.png">


The dryer is also showing as Disconnected because I haven't turned it on since we did some electrical work yesterday.

**Comment by sman591** [comment]
I see. Let me check on this

**Comment by sman591** [comment]
Published a new version that auto-removes disconnected devices. Let me know if that works!

**Comment by kb1ibt** [comment]
I’m going to agree with @raphaelcruzeiro, while it was nice that this patch did remove my disconnected devices, I had specifically asked about being able to manually enter into the config.json file. So that way I had more manual control over the process.

**Comment by sman591** [comment]
Hi all -- this has been fixed in the next release. Offline accessories will only be removed if explicitly asked to in the plugin configuration. Thanks for your patience!
