### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by devin9086** [sman591/homebridge-lg-thinq-ac#46]
I can't seem to log into thinq as it says the password or user id is wrong when it is in fact not wrong.

API Problem?

**Comment by sman591** [comment]
What country code & language code do you have set? Have you tried restarting homebridge once after setting the country & language code?

**Comment by devin9086** [comment]
I'm from Singapore. I have had done changing the country and adding the devices from another country as well. I believe this AC I have uses the legacy API

**Comment by devin9086** [comment]
This refers is in conjunction to #4

**Comment by sman591** [comment]
Do you see a legacy error message/warning printed to the Homebridge log?

**Comment by sman591** [comment]
I'm going to close this but if you have more info let me know
