### ISSUE TITLE
Not usable with a non-US account?

### ISSUE THREAD

**Issue by writingwhilenoodles** [sman591/homebridge-lg-thinq-ac#50]
I'm trying to use the docker, however it seems it's not possible unless you have a US ThinQ account. The URL (https://us.m.lgaccount.com/spx/login/signIn?client_id=LGAO221A02&redirect_uri=https%3A%2F%2Fkr.m.lgaccount.com%2Flogin%2FiabClose&response_type=code&state=de98feff-9772-45bc-b12a-c923a43876f7&country=US&langauge=en-US&svc_list=SVC202&division=ha&show_thirdparty_login=GGL%2CAMZ%2CFBK) does not accept a Dutch Thinq login. It will give the error message 'To use the services please subscribe with an account in the U.S.A.'

Signing up for a USA account is not a viable workaround because the Thinq app from the app store will not accept a USA login, so you would be unable to register the airconditioner to the account.

Normally dutch websites would have 'nl' or 'nl-NL' in the URL instead of US, but that doesn't seem to work here.

**Comment by sman591** [comment]
The country and language codes are customizable- did you specify this in the config.json file? If so, you may need to restart Homebridge once for it to pick up the change

https://github.com/sman591/homebridge-lg-thinq-ac/blob/master/README.md

**Comment by writingwhilenoodles** [comment]
> The country and language codes are customizable- did you specify this in the config.json file? If so, you may need to restart Homebridge once for it to pick up the change
> 
> https://github.com/sman591/homebridge-lg-thinq-ac/blob/master/README.md

That works perfectly, thanks! The readme on Step 3 doesn't mention the possibility/requirement to change the language code, so I didn't try in fear of breaking it.

Sadly my model is not supported, I also posted this in issue #4
