### ISSUE TITLE
Login URL Blank on Hoobs

### ISSUE THREAD

**Issue by coneybeare** [sman591/homebridge-lg-thinq-ac#54]
**LG Air Conditioner Model**
N/A

**Describe the bug**
When trying to log in and setup the account through HOOBS, the Login URL is blank:

````
"platforms": [
        {
            "platform": "LgThinqAirConditioner",
            "plugin_map": {
                "plugin_name": "homebridge-lg-thinq-ac"
            },
            "country_code": "US",
            "language_code": "en-US",
            "refresh_interval": 1
        }
    ]
}
````
![Screen Shot 2020-12-10 at 8 26 53 AM](https://user-images.githubusercontent.com/35369/101778317-b41f9580-3ac1-11eb-990f-9742e5eff40f.png)

**Symptom check**
* **Does your unit appear in the Home app?** N/A
* **Is the current on/off state, temperature, and mode being reported?** N/A
* **Does your unit respond to the controls?** N/A

**Relevant logs**
If you feel there are relevant logs, please include them here. Otherwise you can remove this.

````
12/10/2020, 8:26:03 AM Loaded plugin 'homebridge-lg-thinq-ac'
12/10/2020, 8:26:03 AM [12/10/2020, 6:26:03 AM] Registering platform 'homebridge-lg-thinq-ac.LgThinqAirConditioner'
12/10/2020, 8:26:03 AM Loading 1 platforms...
12/10/2020, 8:26:03 AM [LgThinqAirConditioner] Initializing LgThinqAirConditioner platform...
12/10/2020, 8:26:03 AM Bridge is running on port 51826.
12/10/2020, 8:26:03 AM [LgThinqAirConditioner] Error initializing platform Error: Auth not ready yet, please log in.
````

**Comment by sman591** [comment]
Have you restarted Homebridge after setting the language & country?

**Comment by coneybeare** [comment]
That was it. I had restarted the service, thinking that was enough. A hard reboot of the hooks box did it, thanks!
