### ISSUE TITLE
Please add the Airfilering option for the new generation lg airco

### ISSUE THREAD

**Issue by bart3003** [sman591/homebridge-lg-thinq-ac#56]
Please add de air filtering and air purifier option for the latest generation airco

**Comment by sman591** [comment]
What model is this? Could you provide a product URL to LG's website or link to a manual?

**Comment by bart3003** [comment]
Hello

Model type is AP12RT  Dualcool

https://www.lg.com/nl/air-conditioning/lg-ap12rt


Verstuurd vanaf mijn iPhone

**Comment by xSWIGx** [comment]
Hello!
Same here. Please, add support for this model. Ask me if you need some help. 

Some logs:

`[16/03/2021, 18:46:06] [LgThinqAirConditioner] TargetHeaterCoolerStateCharacteristic: Warning: Your model may support a "drying" or "dehumidification" mode. This is NOT natively supported by Homekit, and using it may show errors in Homebridge or cause temporary instability.
[16/03/2021, 18:46:06] [LgThinqAirConditioner] Starting refresh interval (set to 1 minutes)
[16/03/2021, 18:46:07] [LgThinqAirConditioner] SwingModeCharacteristic: Error parsing state Error: Unsupported API value: 6
[16/03/2021, 18:46:07] [LgThinqAirConditioner] TargetHeaterCoolerStateCharacteristic: Error parsing state Error: Unsupported API value: 5`

**Comment by sman591** [comment]
Interesting!

Could you provide a copy of the snapshot for your device when this happens?

1. Turn on "debug" mode for Homebridge (start Homebridge with `-D` or in the Homebridge UI, go to "Homebridge Settings" and turn on "Homebridge Debug Mode")
2. Restart Homebridge
3. Follow the logs and wait for ~60 seconds
4. Find the line that starts with `device response.result.snapshot` and copy & paste its contents
