### ISSUE TITLE
Thinkq 1 API support

### ISSUE THREAD

**Issue by seungjunProgramming** [sman591/homebridge-lg-thinq-ac#58]
**Is your feature request related to a problem? Please describe.**
The thinq1 API that many people used as an alternative of this project shows an error and is not being updated...
Can you PLZ add support for thinkq1 api???
(I looked at the pinned thread and just asking you)

**Describe alternatives you've considered**
https://github.com/beele/HomebridgeLgSmartThinqAirco (Shows an error and not being updated)

**Comment by sman591** [comment]
Thanks for the heads up -- I have a work in progress for ThinQ 1, but I haven't had time to finish it out. As soon as I do I'll post in #4
