### ISSUE TITLE
request to support model CVT_493401_WW

### ISSUE THREAD

**Issue by rsm1024** [sman591/homebridge-lg-thinq-ac#59]
[LgThinqAirConditioner] Unsupported model: CVT_493401_WW. Please open a GitHub issue at https://github.com/sman591/homebridge-lg-thinq-ac/issues to request support for your model. Falling back to default "POT_056905_WW" model instead.

[LgThinqAirConditioner] TargetHeaterCoolerStateCharacteristic: Error parsing state Error: Unsupported API value: 4

hello, everything is working fine. just this error that appears in homebridge api value 4.

**Comment by sman591** [comment]
Hey there! Thanks for the heads up. What are the different "modes" that your A/C unit supports?

**Comment by rsm1024** [comment]
Hi, thank you for your work

these are the different modes that I saw in the manual

Cooling Mode
Auto Mode or Auto Changeover Dehumidification mode
Heating Mode
Fan Mode

This is the model that I have UV36R +
Module Wifi LG PWFMDD200

https://gscs-b2c.lge.com/downloadFile?fileId=3pDbopOXkdjJNdfjcfN04A

Thank you

Envoyé de mon iPhone

Le 26 janv. 2021 à 08:14, Stuart Olivera <notifications@github.com> a écrit :

﻿

Hey there! Thanks for the heads up. What are the different "modes" that your A/C unit supports?

**Comment by sman591** [comment]
Hey @rsm1024, thanks for your patience! I just pushed up an update to support this (4 fan modes + heating). Could you update to the latest version and let me know if everything still works well?
