### ISSUE TITLE
Configuration with HOOBS

### ISSUE THREAD

**Issue by subsy** [sman591/homebridge-lg-thinq-ac#6]
Hi, thanks for writing this plugin,

I'm trying to configure with HOOBS.

Getting a blank login URL so stuck at this stage.

I see the following in the logs which I assume is related:

> 1:38:55 PM The requested platform "LgThinqAirConditioner" was not registered by any plugin.
> 1:38:55 PM Your config.json is requesting the platform "LgThinqAirConditioner" which has not been published by any installed plugins.

Any idea? Thanks in advance!

**Comment by sman591** [comment]
I’m not familiar with HOOBS- have you specified/installed `homebridge-lg-thinq-ac` as an NPM dependency?

**Comment by subsy** [comment]
I just installed via the HOOBS plugin installer (and then later, to rule that method out as a cause of issues) I uninstalled, and reinstalled via terminal with 

sudo npm -g i homebridge-lg-thinq-ac

The HOOBS plugin management interface looks different to the homebridge-config-ui-x interface. There is no modal dialog presented, instead it looks like this

![image](https://user-images.githubusercontent.com/7700461/82554107-34e66680-9b5d-11ea-821c-1fd1557322b2.png)

I wonder is that URL presented in the logs anywhere that I might be able to find it from?

**Comment by subsy** [comment]
I couldnt get this to work, so ended up replacing my HOOBS install with vanilla homebridge - managed to proceed with setup of the plugin now, but encounter a different issue (same as someone else had already reported): https://github.com/sman591/homebridge-lg-thinq-ac/issues/10

**Comment by sman591** [comment]
Gotcha, thanks for trying with vanilla homebridge! I don't plan on adding support for HOOBS so I'm going to close this, but if you or anyone else sees this and wants to debug it, let me know and I'll be happy to consider a PR for it. Lets continue in #10 and #4 -- I think they're related

**Comment by askovi** [comment]
PR submitted here: https://github.com/sman591/homebridge-lg-thinq-ac/pull/39
