### ISSUE TITLE
please support for RAC_056905_WW

### ISSUE THREAD

**Issue by Fsfz** [sman591/homebridge-lg-thinq-ac#61]
please add support for the RAC_056905_WW model, the lg app is very slow and wanted to control the air conditioning via apple homekit, Thanks.

**Comment by siim911** [comment]
It work fine with me

**Comment by siim911** [comment]
However, i only have an issue with Cool and Heat model. 
following error always appear 

[3/1/2021, 5:21:36 PM] [LgThinqAirConditioner] "M Air Conditioner" (model RAC_056905_WW) uses the thinq1 platform, which is not supported. Please see https://github.com/sman591/homebridge-lg-thinq-ac/issues/4 for updates.
---------------------------------------
SwingModeCharacteristic: Error parsing state Error: Unsupported API value: 1

**Comment by sman591** [comment]
Hi there! Thanks for writing in.

It looks like your device communicates over the legacy ThinQ 1 API, which is not supported yet. Please follow #4 for updates until this is complete
