### ISSUE TITLE
Number of error messages during incialization

### ISSUE THREAD

**Issue by marekzrostlik** [sman591/homebridge-lg-thinq-ac#62]
**LG Air Conditioner Model**
LQ smar airconditioning unit with model name: PC09SQNSJ

**Describe the bug**
The basic control od my A/C units through Homebridge works, however number of error messages is shown in Homebridge log. Copy of log here: [https://www.dropbox.com/s/f1i56xkf49wn21z/log.txt?dl=0]

**Symptom check**
* **Does your unit appear in the Home app?** Yes
* **Is the current on/off state, temperature, and model being reported?** Yes. Model reported differently than on the product sticker. Homebridge shows RAC_056905_WW, but sticker shows PC09SQNSJ.
* **Does your unit respond to the controls?** Yes, even though not to all fucntion control. ONly to the main ones.

**Relevant logs**
If you feel there are relevant logs, please include them here. Otherwise you can remove this.
See here: https://www.dropbox.com/s/f1i56xkf49wn21z/log.txt?dl=0

**Comment by sman591** [comment]
Hmm, this seems very strange -- thanks for providing those logs!

Is this still happening for you? What NodeJS version is running for your Homebridge? I see you have several devices -- are all of them broken, or is it a mix of them?

**Comment by marekzrostlik** [comment]
Hello, yes, still happening. I have NodeJS v14.16.0

The main functions do work fine. I mean on/off, mode heating or cooling, temperature setting. However the other functions like swing do generate these errors.

**Comment by sman591** [comment]
Interesting, I think this might be a recent change on the Homebridge API. I'll need to dig into the changes; I've had my A/C unit turned off for the winter but I'll have it on again soon to test this out. Sorry about that!

**Comment by sman591** [comment]
Actually, I think I see what happened -- your unit and the unit in #63 support different swing modes than what more basic units (and Homekit) support.

I've pushed a fix that should hopefully resolve the errors you're seeing -- could you try upgrading to the new version of this plugin and confirm?

**Comment by marekzrostlik** [comment]
Hello, I tried 1.10.0, but the logs do still containt similar errors:

![image](https://user-images.githubusercontent.com/77804367/115205401-cf4a8380-a0f9-11eb-966d-2d6fe8109c94.png)

**Comment by sman591** [comment]
Hey! This should be fixed now, could you try updating to the latest version?

**Comment by marekzrostlik** [comment]
Hello, just updated the plugin. All error messages disappeared.
Just having a routing issue towards the server on internet:
[20. 4. 2021 10:18:42] [LgThinqAirConditioner] Error initializing platform Error: getaddrinfo ENOTFOUND route.lgthinq.com

All other plugins do work fine, so I wonder, can it be some bug in the plugin? Or just a routing issue?

**Comment by marekzrostlik** [comment]
Hello, I have good news. It works fine. No disrupting error messages.
Obviously, the last time I had a network issue only.

Many thanks for helping me to solve this!

**Comment by sman591** [comment]
Awesome! Thanks for checking
