### ISSUE TITLE
Unable to login to LG with Google account

### ISSUE THREAD

**Issue by fcoclavero** [sman591/homebridge-lg-thinq-ac#67]
I've been unable to complete the plugin setup using my Google account for authentication.

I've already setup my AC with the LG Thinq app for Android and I can control it with no issues within the Thinq app and Google Home. I setup Thinq using the Google OAuth login.

I'm trying to get it configured in the Homebridge plugin, but when I paste the login URL in another browser tab and try to log in using the Google option, as seen bellow:

<img width="796" alt="Screen Shot 2021-04-05 at 23 50 02" src="https://user-images.githubusercontent.com/7874078/113656335-ac37c280-9669-11eb-9f5a-e58eff1a79b4.png">

> Note: the screenshot is in Spanish. My country code is `CL` and my and my language code is `en-CL`. 

I get the following error message:

<img width="508" alt="Screen Shot 2021-04-05 at 23 44 51" src="https://user-images.githubusercontent.com/7874078/113656277-89a5a980-9669-11eb-97e4-35729b0e763c.png">

Any ideas? I can get you any further information you might need.

Thanks a lot!

**Comment by sman591** [comment]
Hmm very interesting, I see the same issue with `CL` / `en-CL`.

What if you take "Login URL" and convert the cl.m.lgaccount.com to us.m.lgaccount.com, then open that URL? Are you able to successfully log in?

<img width="365" alt="Screen Shot 2021-04-05 at 11 52 39 PM" src="https://user-images.githubusercontent.com/1441807/113670470-03d62e00-966a-11eb-971e-bbbadbf9cb26.png">

**Comment by fcoclavero** [comment]
Hey @sman591 thanks for the quick reply! Manually changing the "Login URL" as suggested I was able to login succesfully. Thanks a lot!

Unluckily though, I ended up in issue #4 :( If there's anythin I can help you with, just let me know!

**Comment by designerferro** [comment]
Hey. Nice work here.

From my try and error over at Home-assistant with WideQ, and several other unfinished implementations, it seems that you can't use the API authenticating with any other then an LG account. Meaning, you will have to enroll with a valid email address and setup a password over at the LG login page. Also keep in mind the have separated V1 and V2 API implementations, but credentials are the same for both implementations. (Thanks for not messing that one up)

**Comment by sman591** [comment]
Hey all, I tried to fix this in b0b821c. Google / etc logins should work from now on; let me know if you have any issues with it.
