### ISSUE TITLE
Unable to login to LG using Google (SG)

### ISSUE THREAD

**Issue by ethantrainshard** [sman591/homebridge-lg-thinq-ac#69]
Nice work you have here for the plugin.

Tried to login using Google, there is this Authorisation Error.

Followed #67 to see whether this issue will be resolved, but no avail.

<img width="503" alt="image" src="https://user-images.githubusercontent.com/52568986/114150714-f01f1600-994e-11eb-8470-10a5f9059f5f.png">

Country code is SG, language is en-SG.

**Comment by sman591** [comment]
Hey @ethantrainshard, have you tried replacing the "sg.m.lgaccount.com" with "us.m.lgaccount.com" in the URL? That seemed to fix it in the small test I made; if this is repeatable I'll send a plugin update with it.

**Comment by ethantrainshard** [comment]
Hi @sman591, thanks for the update! Yes, it is working now!

**Comment by sman591** [comment]
Awesome! I'll close this as a dupe of #67 - will update that once I have this fixed permanently. Stay tuned for #4.
