### ISSUE TITLE
Ac not showing in Home App but showing in Homebridge

### ISSUE THREAD

**Issue by techface10** [sman591/homebridge-lg-thinq-ac#73]
Ac added to my homebridge and it is showing on my Accessories tab but it is not showing in Home App. The below-mentioned error keeps showing in my log. Are there any Solutions?

[4/25/2021, 11:21:16 AM] [homebridge-lg-thinq-ac] SwingModeCharacteristic: Warning: Your A/C unit supports variable swing settings, but this is not supported by Homekit. Ignoring desired swing setting.

**Comment by IMNotMax** [comment]
Same issue here with my wall mounted LG units.
I can control ON/OFF, temperature and mode in the homebridge accessories but homekit doe not show these accessories.

**Comment by IMNotMax** [comment]
Ah ah ah ah, just after posting the "Issue" I realized I forget to add the bridge to homekit. #Noob !
Works great! @techface10 did you use the plugin as secondary bridge ? Or as a standard plugin in homebridge ?

**Comment by IMNotMax** [comment]
Ok, after a few days of use, I see a pattern. 
With the secondary bridge mode or with direct plugin.
Every 48h or so the plugin crashes and the device is not reachable from the Home App but still works from homebridge accessories.
I was not able to spot the logs before I understand this pattern. Will post here.

Last behavior, even after restarting homebridge, accessories are still unreachable in the Home App. I have to delete the accessories form homebridge, restart to have the accessories back in the Home App.

And by the way, @sman591 great work ! And thank you for your time !

**Comment by sman591** [comment]
Can you update to the latest version and let me know if this still happens?

**Comment by IMNotMax** [comment]
no more issues after a 10 days test 👍 
Nice !!!!

**Comment by sman591** [comment]
Sweet!

**Comment by IMNotMax** [comment]
Happy to help !
