### ISSUE TITLE
Suppress logging about unsupported features (SwingModeCharacteristic)

### ISSUE THREAD

**Issue by mishakim** [sman591/homebridge-lg-thinq-ac#80]
**Is your feature request related to a problem? Please describe.**
My logs are absolutely swamped with the following:
`[5/18/2021, 8:41:33 AM] [LgThinqAirConditioner] SwingModeCharacteristic: Warning: Your A/C unit supports variable swing settings, but this is not supported by Homekit. Ignoring desired swing setting.`
I have this once a minute, obscuring anything else that might be in the logs. I do have five units, I assume this is multiplying the problem.

**Describe the solution you'd like**
Throw this error once (per unit would be OK) on startup, but don't repeat it after that

**Additional context**
I have five units across two models:
LSN120HSV5 / RAC_056905_WW
LSN090HSV5 / RAC_056905_WW
(both report same internal model no)

**Comment by sman591** [comment]
Thanks for noting - that should definitely only appear once
