### ISSUE TITLE
2 identical units, one not supported?

### ISSUE THREAD

**Issue by fleeeecy** [sman591/homebridge-lg-thinq-ac#82]
I (finally!) managed to get this plugin to work by getting rid of Sign In With Apple and using a standard LG account auth instead. 

Now I'm facing a different issue. I own two seemingly identical LP1419IVSM units; the first is about 2 years old, while I just purchased the second one. 

The second, newer unit is recognized and works well with Homebridge (Impressive!) However, the older unit is triggering this error in the log. 

[LgThinqAirConditioner] Discover found 2 total devices
[LgThinqAirConditioner] "Chambre" (model POT_056905_WW) uses the thinq1 platform, which is not supported. Please see https://github.com/sman591/homebridge-lg-thinq-ac/issues/4 for updates.

Interestingly, both units have the same model POT_056905_WW.

Is there something I can do to fix this? Thank you for making this plugin!

**Comment by fleeeecy** [comment]
According to the LG ThinQ app, the software version for the unit that is triggering the error is the following : 

16.32 / 2.6.2_RTOS_3K / SAA40115101.00005101.0 / SAA40115201.0000045b.0

**Comment by sman591** [comment]
Yeah, unfortunately your 2-year-old unit is on an older LG API that I haven't finished building support for. Please follow #4 for updates, though I don't have any guarantee on if or when that support may come
