### ISSUE TITLE
LG PA11WS - works correctly

### ISSUE THREAD

**Issue by PrzemyslawKlys** [sman591/homebridge-lg-thinq-ac#86]
**LG Air Conditioner Model**
LG PA11WS, in homekit: POT_056905_WW

Just wanted to let you know that I've just bought this portable LG and it works correctly in Homebridge/HomeKit. Not sure if you have a list of "tested/works" but maybe it would be worth adding, a list in the readme that people can expand on, so when people will consider buying LG they may decide this based on what is supported and works, and what may not work. 

I do consider buying multiple models of LG for my home so I will have more to test soon.

**Comment by sman591** [comment]
Nice, thank you! I'll add this to the readme. Let me know if you find others to also be fully functional.

**Comment by sman591** [comment]
Added in ffedffd
