### ISSUE TITLE
Full support for WIN_056905_WW

### ISSUE THREAD

**Issue by rjhewitt3** [sman591/homebridge-lg-thinq-ac#95]
My AC hadn’t been showing up, but just appeared a few minutes ago. Got some code output from Homekit to share, hopefully helps give info for ful support?

All available features may already be available, but HomeKit seems to thing there is more to be added, according to their notification:

![63A2DCE6-C8B0-484F-B45A-804599ABC734](https://user-images.githubusercontent.com/6742828/132978862-3d7d5e7b-ad8d-42ed-aa96-f155b5dc591b.jpeg)

> {
>   "bridgedAccessories" : [
> 
>   ],
>   "manufacturer" : "LG",
>   "model" : "WIN_056905_WW",
>   "services" : [
>     {
>       "type" : "0000003E-0000-1000-8000-0026BB765291",
>       "name" : "Dining Room AC",
>       "characteristics" : [
>         {
>           "metadata" : {
>             "format" : "bool",
>             "description" : "Identify"
>           },
>           "notify" : false,
>           "write" : true,
>           "properties" : [
>             "HMCharacteristicPropertyWritable"
>           ],
>           "type" : "00000014-0000-1000-8000-0026BB765291",
>           "read" : false
>         },
>         {
>           "notify" : false,
>           "write" : false,
>           "read" : true,
>           "value" : "LG ",
>           "type" : "00000020-0000-1000-8000-0026BB765291",
>           "metadata" : {
>             "format" : "string",
>             "description" : "Manufacturer"
>           },
>           "properties" : [
>             "HMCharacteristicPropertyReadable"
>           ]
>         },
>         {
>           "notify" : false,
>           "write" : false,
>           "read" : true,
>           "value" : "WIN_056905_WW ",
>           "type" : "00000021-0000-1000-8000-0026BB765291",
>           "metadata" : {
>             "format" : "string",
>             "description" : "Model"
>           },
>           "properties" : [
>             "HMCharacteristicPropertyReadable"
>           ]
>         },
>         {
>           "notify" : false,
>           "write" : false,
>           "read" : true,
>           "value" : "Dining Room AC ",
>           "type" : "00000023-0000-1000-8000-0026BB765291",
>           "metadata" : {
>             "format" : "string",
>             "description" : "Name"
>           },
>           "properties" : [
>             "HMCharacteristicPropertyReadable"
>           ]
>         },
>         {
>           "notify" : false,
>           "write" : false,
>           "read" : true,
>           "value" : "Unknown ",
>           "type" : "00000030-0000-1000-8000-0026BB765291",
>           "metadata" : {
>             "format" : "string",
>             "description" : "Serial Number"
>           },
>           "properties" : [
>             "HMCharacteristicPropertyReadable"
>           ]
>         },
>         {
>           "notify" : false,
>           "write" : false,
>           "read" : true,
>           "value" : "1.2.0 ",
>           "type" : "00000052-0000-1000-8000-0026BB765291",
>           "metadata" : {
>             "format" : "string",
>             "description" : "Firmware Revision"
>           },
>           "properties" : [
>             "HMCharacteristicPropertyReadable"
>           ]
>         }
>       ]
>     },
>     {
>       "type" : "000000BC-0000-1000-8000-0026BB765291",
>       "name" : "Dining Room AC",
>       "characteristics" : [
>         {
>           "notify" : false,
>           "write" : false,
>           "read" : true,
>           "value" : "Dining Room AC ",
>           "type" : "00000023-0000-1000-8000-0026BB765291",
>           "metadata" : {
>             "format" : "string",
>             "description" : "Name"
>           },
>           "properties" : [
>             "HMCharacteristicPropertyReadable"
>           ]
>         },
>         {
>           "notify" : true,
>           "write" : true,
>           "read" : true,
>           "value" : "No",
>           "type" : "000000B0-0000-1000-8000-0026BB765291",
>           "metadata" : {
>             "description" : "Active",
>             "min" : 0,
>             "max" : 1,
>             "step" : 1,
>             "format" : "uint8"
>           },
>           "properties" : [
>             "HMCharacteristicPropertyWritable",
>             "HMCharacteristicPropertyReadable",
>             "HMCharacteristicPropertySupportsEventNotification"
>           ]
>         },
>         {
>           "notify" : true,
>           "write" : false,
>           "read" : true,
>           "value" : "Inactive",
>           "type" : "000000B1-0000-1000-8000-0026BB765291",
>           "metadata" : {
>             "description" : "Current Heater-Cooler State",
>             "min" : 0,
>             "max" : 3,
>             "step" : 1,
>             "format" : "uint8"
>           },
>           "properties" : [
>             "HMCharacteristicPropertyReadable",
>             "HMCharacteristicPropertySupportsEventNotification"
>           ]
>         },
>         {
>           "notify" : true,
>           "write" : true,
>           "read" : true,
>           "value" : "Cool",
>           "type" : "000000B2-0000-1000-8000-0026BB765291",
>           "metadata" : {
>             "description" : "Target Heater-Cooler State",
>             "min" : 0,
>             "max" : 2,
>             "step" : 1,
>             "format" : "uint8"
>           },
>           "properties" : [
>             "HMCharacteristicPropertyWritable",
>             "HMCharacteristicPropertyReadable",
>             "HMCharacteristicPropertySupportsEventNotification"
>           ]
>         },
>         {
>           "notify" : true,
>           "write" : false,
>           "read" : true,
>           "value" : "59.0°F",
>           "type" : "00000011-0000-1000-8000-0026BB765291",
>           "metadata" : {
>             "description" : "Current Temperature",
>             "min" : 10,
>             "max" : 39,
>             "step" : 0,
>             "format" : "float"
>           },
>           "properties" : [
>             "HMCharacteristicPropertyReadable",
>             "HMCharacteristicPropertySupportsEventNotification"
>           ]
>         },
>         {
>           "notify" : true,
>           "write" : true,
>           "read" : true,
>           "value" : "64.4°F",
>           "type" : "0000000D-0000-1000-8000-0026BB765291",
>           "metadata" : {
>             "description" : "Cooling Threshold Temperature",
>             "min" : 18,
>             "max" : 30,
>             "step" : 0,
>             "format" : "float"
>           },
>           "properties" : [
>             "HMCharacteristicPropertyWritable",
>             "HMCharacteristicPropertyReadable",
>             "HMCharacteristicPropertySupportsEventNotification"
>           ]
>         },
>         {
>           "notify" : true,
>           "write" : true,
>           "read" : true,
>           "value" : "64.4°F",
>           "type" : "00000012-0000-1000-8000-0026BB765291",
>           "metadata" : {
>             "description" : "Heating Threshold Temperature",
>             "min" : 18,
>             "max" : 30,
>             "step" : 0,
>             "format" : "float"
>           },
>           "properties" : [
>             "HMCharacteristicPropertyWritable",
>             "HMCharacteristicPropertyReadable",
>             "HMCharacteristicPropertySupportsEventNotification"
>           ]
>         },
>         {
>           "notify" : true,
>           "write" : true,
>           "read" : true,
>           "value" : "20.0 % Rotation Speed",
>           "type" : "00000029-0000-1000-8000-0026BB765291",
>           "metadata" : {
>             "description" : "Rotation Speed",
>             "min" : 0,
>             "max" : 5,
>             "step" : 0,
>             "format" : "float"
>           },
>           "properties" : [
>             "HMCharacteristicPropertyWritable",
>             "HMCharacteristicPropertyReadable",
>             "HMCharacteristicPropertySupportsEventNotification"
>           ]
>         },
>         {
>           "notify" : true,
>           "write" : true,
>           "read" : true,
>           "value" : "Disabled",
>           "type" : "000000B6-0000-1000-8000-0026BB765291",
>           "metadata" : {
>             "description" : "Swing Mode",
>             "min" : 0,
>             "max" : 1,
>             "step" : 1,
>             "format" : "uint8"
>           },
>           "properties" : [
>             "HMCharacteristicPropertyWritable",
>             "HMCharacteristicPropertyReadable",
>             "HMCharacteristicPropertySupportsEventNotification"
>           ]
>         }
>       ]
>     },
>     {
>       "type" : "00000049-0000-1000-8000-0026BB765291",
>       "name" : "Auto Mode",
>       "characteristics" : [
>         {
>           "notify" : false,
>           "write" : false,
>           "read" : true,
>           "value" : "Auto Mode ",
>           "type" : "00000023-0000-1000-8000-0026BB765291",
>           "metadata" : {
>             "format" : "string",
>             "description" : "Name"
>           },
>           "properties" : [
>             "HMCharacteristicPropertyReadable"
>           ]
>         },
>         {
>           "notify" : true,
>           "write" : true,
>           "read" : true,
>           "value" : "Turned off",
>           "type" : "00000025-0000-1000-8000-0026BB765291",
>           "metadata" : {
>             "format" : "bool",
>             "description" : "Power State"
>           },
>           "properties" : [
>             "HMCharacteristicPropertyWritable",
>             "HMCharacteristicPropertyReadable",
>             "HMCharacteristicPropertySupportsEventNotification"
>           ]
>         }
>       ]
>     },
>     {
>       "type" : "00000002-0000-1000-8000-0026BB765291",
>       "name" : "HOOBS",
>       "characteristics" : [
>         {
>           "notify" : false,
>           "write" : false,
>           "read" : true,
>           "value" : "HOOBS ",
>           "type" : "00000023-0000-1000-8000-0026BB765291",
>           "metadata" : {
>             "format" : "string",
>             "description" : "Name"
>           },
>           "properties" : [
>             "HMCharacteristicPropertyReadable"
>           ]
>         },
>         {
>           "notify" : true,
>           "write" : false,
>           "read" : true,
>           "value" : "homebridge-lg-thinq ",
>           "type" : "00000004-0000-1000-8000-0026BB765291",
>           "metadata" : {
>             "format" : "string",
>             "description" : "Plugin ID"
>           },
>           "properties" : [
>             "HMCharacteristicPropertyReadable",
>             "HMCharacteristicPropertySupportsEventNotification"
>           ]
>         },
>         {
>           "notify" : true,
>           "write" : false,
>           "read" : true,
>           "value" : "d27d61a0-7149-11d3-80ba-0051edea67c5 ",
>           "type" : "00000003-0000-1000-8000-0026BB765291",
>           "metadata" : {
>             "format" : "string",
>             "description" : "Device ID"
>           },
>           "properties" : [
>             "HMCharacteristicPropertyReadable",
>             "HMCharacteristicPropertySupportsEventNotification"
>           ]
>         }
>       ]
>     }
>   ],
>   "name" : "Dining Room AC",
>   "category" : "0FBA259B-05AC-46F2-875F-204ABB6D9FE7"
> }

**Comment by sman591** [comment]
Thanks! There are a few others here that use a `WIN_056905_WW` model, so I think this should be working.

Where are you seeing this error message? Does it say what the incompatibility is?

Feel free to re-open if there's still warnings

**Comment by rjhewitt3** [comment]
Hey, sorry for the delay. My Homebridge install got corrupted and I was out of town for a bit. I'm back online now though and tried to run through this again and this isn't working for me. I'm getting an error:

`4/1/2022, 8:02:58 PMLG ThinQ AC BridgeLgThinqAirConditionerERROR"Dining Room AC" (model WIN_056905_WW) uses the thinq1 platform, which is not supported. Please see https://github.com/sman591/homebridge-lg-thinq-ac/issues/4 for updates.`

It referred to issue #4 in the error for whatever reason.

**Comment by rjhewitt3** [comment]
Also, it's not giving me the option to re-open—I assume because I'm not a contributor.

**Comment by sman591** [comment]
I'm not sure why re-open is hidden, but this looks indeed like issue #4 which I'd merge this into
