### ISSUE TITLE
LG S4NQ09WA51A.EB2GAMZ - Works fine.

### ISSUE THREAD

**Issue by biosim500** [sman591/homebridge-lg-thinq-ac#97]
Just to let you guys know, the LG S4NQ09WA51A.EB2GAMZ 220v 9000btu works fine.

The hardware doesn't heat, just cool, and in HK it shows "Heating/Cooling/Auto", but's ok. 

I hope in a future we can hide the Heat mode.

**Comment by sman591** [comment]
Good to know! I can add this to the readme.

Does it support a “dry” or “dehumidify” option? That’s what I have mine mapped to right now for “heat” since HK doesn’t let us change the label

**Comment by biosim500** [comment]
Yeah it does suport the Dehumidify! But, unfortunaly, i don't know how to map to this option.

Btw, i'm getting this "error" from time to time =
"[homebridge-lg-thinq-ac] This plugin generated a warning from the characteristic 'Filter Life Level': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info."

The AC doens't show when the filter needs to be cleaned, so maybe that's why this shows.

**Comment by sman591** [comment]
Thanks! The log error has been fixed in 22f0aa6007dc4ee993aed383e3c35afcc2707fd4, follow #94 for a fix for filter life being accurate

What model is your unit? It should display in the Home app under "Model"

**Comment by sman591** [comment]
Note added in ffedffd
