### ISSUE TITLE
Homebridge can connect and display AC parameter but can't change any set setpoint

### ISSUE THREAD

**Issue by aprylwine** [sman591/homebridge-lg-thinq-ac#98]
Homebridge can connect and display AC parameter but can't change any set setpoint

**Comment by aprylwine** [comment]
Model : RAC_056905_WW

**Comment by sman591** [comment]
Please reopen this issue after attaching any relevant logs to assist with debugging. It'd be best to turn on debug mode for Homebridge and send along anything that sticks out. Thank you!
